version: '3.9'

services:
  app:
    build:
      context:  docker
      dockerfile: dockerfile
    container_name: API_olho_de_delfos
    user: "1000:1000" #Garante que os arquivos serão criados como root
    ports:
      - "8070:80"     #HTTP Lembrando que a esquerda é a da máquina e a doreita é a do conteiner
      - "4213:443"    #HTTPS
    volumes:
      - ./:/app       #Monta a raiz do projeto no container
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300

  db:
    image: postgres:14.4
    container_name: postgres_delfos
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5420:5432"

  redis:
    image: redis:7-alpine
    container_name: delfos_redis
    ports:
      - "6360:6379"

volumes:
  pgdata:
